### ISSUE TITLE
Image component gets 401 on image requests when using Netlify Password protection

### ISSUE THREAD

**Issue by AlaricBaraou** [netlify/netlify-plugin-nextjs#661] opened 2021-09-20 08:40 UTC
**Describe the bug**
The Image component breaks when using Netlify Password protection feature

**To Reproduce**
Activate Netlify Password protection feature on a site using the Image component 
Access the website
All images request end up with a 401 unauthorised response

**Expected behavior**
Images load correctly

**Versions**
- Next.js: 11.0.1

Let me know if I need to provide more informations.
For now I disabled the password protection but this is not convenient.

**Comment by mhatvan** [comment] 2021-09-20 14:40
Duplicate of https://github.com/netlify/netlify-plugin-nextjs/issues/553

**Closed** 2021-09-21 08:36 UTC
