### ISSUE TITLE
[next_image] Fails to load most of JPG images. (Input buffer contains unsupported image format)

### ISSUE THREAD

**Issue by TheFullResolution** [netlify/netlify-plugin-nextjs#312] opened 2021-05-16 03:44 UTC
**Description**

I am trying to migrate a small project to Next.js to Netlfy, I was waiting for the release of new image support, and it works great when it works. However, now, the new version can't process half of the images on the page. I can't completely determine why. I even processed all images locally to optimize the image size.

1. Go to https://graweria-new.netlify.app
3. Scroll down to the image gallery and observe how most of the images failed to load. 
4. See 502 errors in the dev tools.

Here are the logs:

`5:36:27 AM: 433f157c ERROR  Invoke Error 	{"errorType":"Error","errorMessage":"Input buffer contains unsupported image format","stack":["Error: Input buffer contains unsupported image format"]}`

![Screenshot 2021-05-16 053928](https://user-images.githubusercontent.com/11708648/118384775-2a906880-b609-11eb-83e5-0fc864783e33.png)

Here is one of the images failing:
![shop_inside (2)](https://user-images.githubusercontent.com/11708648/118384804-5a3f7080-b609-11eb-8c51-46dc9fc02cf8.jpg)

**Expected behavior**
Images are loaded

**Versions**
- Next.js: "10.2.0"
- plugin (if installed at fixed version): latest

**Comment by TheFullResolution** [comment] 2021-05-16 03:47
I realized that GitHub is processing the image example
[uploads.zip](https://github.com/netlify/netlify-plugin-nextjs/files/6488673/uploads.zip)
 so here is a zip with original files

**Comment by ascorbic** [comment] 2021-05-17 12:29
Hi @TheFullResolution 
Thanks for the report. It seems to be caused by incorrect handling of redirects with spaces in them. I've reported this internally and will also be pushing a fix in the plugin with a workaround. In the meantime, renaming the image to remove the space fixes the error. I'll try and give more helpful error messages too: the "unsupported image format" was actually an HTML 404 page!

**Comment by TheFullResolution** [comment] 2021-05-18 03:39
Nice, thank you for a quick reaction! Looking forward to your PR @ascorbic

**Comment by ascorbic** [comment] 2021-05-18 16:09
Fixed in #317

**Closed by ascorbic** 2021-05-18 16:09 UTC
Labels: next/image, priority: high, type: bug

**Comment by TheFullResolution** [comment] 2021-05-24 04:33
@ascorbic, do you know when this fix will be released?
