### ISSUE TITLE
`basePath` option is not working

### ISSUE THREAD

**Issue by vitorbal** [netlify/netlify-plugin-nextjs#131] opened 2021-03-12 17:49 UTC
**Describe the bug**
If you set up a very simple nextjs app with the `basePath` option configured, the deployed website will 404 a bunch of static asset paths. Here's an example for a `basePath` of `/cats-of-zapier`:

![](https://cdn.zapier.com/storage/photos/791abae0703ab656a56bdc2ca0cfdafd.png)

**To Reproduce**
1. Create a new next.js app
2. Add `basePath: '/foo'` to `next.config.js`
3. Deploy the app to netlify
4. Navigate to the deployment and notice how all of the prefixed assets 404

**Expected behavior**
For the app to be served correctly, with no 404s.

**Versions**
- Next.js: 10.0.7
- plugin (if installed at fixed version): latest, I guess? Enabled from the Netlify UI

**Comment by jlengstorf** [comment] 2021-03-12 18:05
hey, @vitorbal! do you have a reproduction available for us to review? and/or the build logs for the failing deploy? that helps us track things down much more quickly

thank you!

**Comment by jdeal** [comment] 2021-03-14 04:55
@vitorbal does [this forum post](https://answers.netlify.com/t/next-js-site-with-basepath-config-gets-ignored-on-netlify-deploy/23676) help?

**Comment by vitorbal** [comment] 2021-03-14 11:19
@jlengstorf thanks!

* reproduction case: https://github.com/vitorbal/netlify-next-basepath
* app deployed on netlify: https://604defe6294def94d336b2a7--hungry-chandrasekhar-0c40c1.netlify.app/
* build logs: https://gist.github.com/vitorbal/4cf9edbaa6e205eb0c8707a3e956d753

as you can see `/` is serving what should be served by `/foo`, and all the static assets 404. If you try navigating to `/foo`, it 404s, so something is wrong with the runtime there.

**Comment by vitorbal** [comment] 2021-03-14 11:21
@jdeal thanks for sharing that forum post! It _sort of_ helps, but in their case, they are deploying an app via `next export`. I'm interested in deploying a next app in serverless mode, so this plugin can be leveraged to support SSRd pages, etc.

**Comment by jlengstorf** [comment] 2021-03-15 16:20
hey, @vitorbal — I think I know the issue here. with `basePath`, the assumption is that the site will be served from `https://example.com/foo/`, so you'd redirect to your app like so:

```
/foo/*  https://604defe6294def94d336b2a7--hungry-chandrasekhar-0c40c1.netlify.app/:splat  200
```

I set up an example of this:

- parent site (redirects to the next site at `/foo`): https://keen-hamilton-aebe60.netlify.app/foo
- Next site: https://adoring-bardeen-d8f372.netlify.app/

source code:
- parent site: https://github.com/jlengstorf/next-basepath-poc
- Next site is a fork of your repro

let me know if this makes sense. thanks!

**Comment by lindsaylevine** [comment] 2021-03-19 09:21
hey @vitorbal! did jason's comment solve your issue? let us know so we can close the issue or continue to try to help! :D

**Comment by vitorbal** [comment] 2021-03-22 15:25
Howdy folks! Apologies for the lul.

@jlengstorf I checked out your app and even though it solves the problem, I would expect a standalone next.js app to work without those redirects.

If you run your next app locally, the `basePath` config works without a problem, so I would expect it to work once deployed too. Similarly, if you deploy your next app to a node server instead of a serverless platform like Netlify, the `basePath` config also works without any redirects.

If it helps, I deployed the reproduction case to Vercel and it also works as expected there: https://next-basepath.vercel.app/foo

**Comment by lunelson** [comment] 2021-03-22 18:51
@vitorbal @jlengstorf I've just run in to this too. I don't think redirecting from root to a subpath is the right solution. It means your site is then _only_ usable as a redirect from another site, since otherwise you could easily create a loop. 

When I run `next build` and then `next start` on my site locally, it serves the built site under the subpath (in my case `/blog`), and that's the way it should work here too.

**Comment by lindsaylevine** [comment] 2021-03-23 00:56
@vitorbal @lunelson hello! i'll explore how we might solve this within the plugin. will let you know!!!

**Comment by vitorbal** [comment] 2021-03-23 09:29
@lindsaylevine @jlengstorf sounds good, thank you both for being so responsive!

**Closed** 2021-06-03 09:50 UTC
Labels: priority: medium, type: bug
