### ISSUE TITLE
Trailing slash remains in the url

### ISSUE THREAD

**Issue by alisakova** [netlify/netlify-plugin-nextjs#631] opened 2021-09-01 10:55 UTC
**Describe the bug**
Hello everyone. My team faced with an issue that trailing slash at the end of the url doesn't redirect user to the url without slash. If we read next docs, we can see: 
`By default Next.js will redirect urls with trailing slashes to their counterpart without a trailing slash.`

What can we do in order to redirect url with slash to the url without slash? 

**Versions**
- Next.js: 10.0.9
- plugin (if installed at fixed version): latest

**Comment by lindsaylevine** [comment] 2021-09-01 14:36
@alisakova hello! i _think_ this might be a duplicate of https://github.com/netlify/netlify-plugin-nextjs/issues/256, but it also seems like the _opposite_ problem at the same time. do you have trailingSlash set to true in your next.config.js? all of the users on issue 256 are asserting that that does not work on netlify.

**Comment by alisakova** [comment] 2021-09-01 14:37
@lindsaylevine yep, I saw that issue also. No, I don't have trailingSlash as true in next.config.js.

**Comment by lindsaylevine** [comment] 2021-09-01 15:16
@alisakova hm, then i'm not quite sure how your urls are getting trailing slashes? sounds like i need a repo that reproduces your issue to figure out what's going on.

**Comment by alisakova** [comment] 2021-09-01 15:18
@lindsaylevine If you put it on purpose. We don't have it by default. But if I type in the url address something like "www.test.com/", this slash remains

**Comment by alisakova** [comment] 2021-09-02 11:26
@lindsaylevine I guess all pages have this bug. I've just checked: getStatisProps or getServerSideProps don't matter

**Comment by lindsaylevine** [comment] 2021-09-02 11:33
@lindsaylevine it depends what youre doing in getStaticProps. if you're using fallback: true or fallback: blocking and pages are built on demand, you'll have the same issue. same if you're using revalidate. if you want me to take a closer look, please provide a repo!

**Comment by lindsaylevine** [comment] 2021-09-02 11:34
demo ->

SSR'd page https://basepath-testing.netlify.app/random/ maintains trailing slash as you reported
pre-rendered page https://basepath-testing.netlify.app/matt/1/ removes trailing slash

**Comment by alisakova** [comment] 2021-09-02 11:36
@lindsaylevine oh I see. We have some pages with getStaticProps + getStaticPaths + fallback: false, but slash still remains. 
Unfortunately I can't provide repo :( 
But I see in your example that it works fine for you

**Comment by lindsaylevine** [comment] 2021-09-02 13:32
@alisakova most users [have to] create entirely separate/new repositories from whatever project theyre working on. they dont share their actual project. 

i'll leave this issue open to remember to address function trailing slashes in our plugin rewrite.

**Comment by alisakova** [comment] 2021-09-02 18:04
@lindsaylevine https://github.com/alisakova/next
https://amazing-leakey-16e3a3.netlify.app/pokemon/
If I do everything right, this can be an example

**Comment by lindsaylevine** [comment] 2021-09-02 18:09
@alisakova thank you so much! i can definitely see the slash remains in the url, which is strange!

do you want guidance on how to possibly work around this, or is this a low priority for you?

**Comment by alisakova** [comment] 2021-09-02 18:10
@lindsaylevine if you have any guidance, it will be super, because it's very important for our project!

**Comment by lindsaylevine** [comment] 2021-09-03 08:25
@alisakova i did some digging and it seems like the slashes on your pre-rendered pages are because of the way we handle i18n with redirects in our plugin. can you help me understand why the trailing slash (when forced there) is very important for your project?

**Comment by lindsaylevine** [comment] 2021-09-03 08:26
(only because now the workaround would be more complicated and maybe i can think of something else if i better understand your problem)

**Comment by alisakova** [comment] 2021-09-03 08:27
@lindsaylevine guys from seo want to remove it. :)

**Comment by lindsaylevine** [comment] 2021-09-03 08:46
💀 ok well i just did some poking and this would require work on my end that i just don't have the bandwidth for right now :'(. i'd hang tight for the plugin rewrite and just tell your seo folks to blame it on us 💔

**Comment by alisakova** [comment] 2021-09-03 09:02
@lindsaylevine thank you so much for your help anyway!

**Comment by ascorbic** [comment] 2021-10-01 20:28
This is fixed in the upcoming plugin version: https://next-trailing-slash.netlify.app/pokemon/pikachu/

**Comment by ascorbic** [comment] 2021-11-01 11:16
Fixed in v4

**Closed by ascorbic** 2021-11-01 11:16 UTC
Labels: type: bug, priority: low, rewrite candidate, fixed in upcoming release
