### ISSUE TITLE
[Bug]: Next.js 12.0.7 using pnpm returns: `Could not find Next.js server`

### ISSUE THREAD

**Issue by zaiste** [netlify/netlify-plugin-nextjs#992] opened 2021-12-14 17:29 UTC
### Steps to reproduce

1. Clone the provided repository
2. In the Netlify UI, set the `Publish directory` to `.next`
3. In the Netlify UI, set the `Build command` to `npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build`

### A link to a reproduction repository

https://github.com/saleor/react-storefront

### Plugin version

4.0.0

### More information about your build

- [X] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### Your `netlify.toml` file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Relevant log output (or link to your logs)

[Live demo](https://hungry-leakey-c20000.netlify.app)

<details>
  <summary>Build logs</summary>
  
```
{
  "errorType": "Error",
  "errorMessage": "Could not find Next.js server",
  "trace": [
    "Error: Could not find Next.js server",
    "    at getNextServer (/var/task/.netlify/functions-internal/___netlify-handler/handlerUtils.js:157:19)",
    "    at /var/task/.netlify/functions-internal/___netlify-handler/___netlify-handler.js:31:24",
    "    at Object.<anonymous> (/var/task/.netlify/functions-internal/___netlify-handler/___netlify-handler.js:91:3)",
    "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
    "    at Module.load (internal/modules/cjs/loader.js:950:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
    "    at Module.require (internal/modules/cjs/loader.js:974:19)",
    "    at require (internal/modules/cjs/helpers.js:93:18)",
    "    at Object.<anonymous> (/var/task/___netlify-handler.js:1:18)"
  ]
}

```

</details>

**Comment by ascorbic** [comment] 2021-12-15 10:28
Hi @zaiste 
Thanks for the report. I've done some testing and it seems the issue is related to using pnpm. It looks liek when we bundle the node modules for the functions, we're not including the symlinks, so the `node_modules/next` modules are just empty folders, even though all of the modules are actually there in `node_modules/.pnpm`. I'm going to open a separate issue on the zip-it-and-ship-it repo to handle this properly. In the meantime the only workaround I can suggest is to use npm or yarn.

**Comment by ascorbic** [comment] 2021-12-15 10:41
I've updated the title to make it easier for other pnpm users to find. Once I find out how soon the fix is likely to be I may add a specific check in the plugin to ensure that at least it has a mroe helpful error message

**Comment by ascorbic** [comment] 2021-12-21 14:40
@zaiste This was fixed in https://github.com/netlify/zip-it-and-ship-it/pull/792, and in my fork now works with pnpm!

**Closed by ascorbic** 2021-12-21 14:40 UTC
Labels: type: bug

**Comment by zaiste** [comment] 2021-12-21 16:43
@ascorbic that was fast! thanks! :)
