### ISSUE TITLE
Plugin stuck on copying pre-rendered pages to out folder -> Timeout

### ISSUE THREAD

**Issue by pReya** [netlify/netlify-plugin-nextjs#263] opened 2021-05-03 17:07 UTC
**Describe the bug**
I updated some dependencies in my project, and now I am stuck in the `@netlify/plugin-nextjs` build process in the step `Copying pre-rendered pages with getStaticProps and JSON data to out`. Nothing happens after this log output. The script is just frozen. On CI I get a timeout after reaching the maximum run time of my job. There is no error logged anywhere in the console.

```
────────────────────────────────────────────────────────────────
  3. onBuild command from @netlify/plugin-nextjs                
────────────────────────────────────────────────────────────────

** Running Next on Netlify package **
🚀 Next on Netlify 🚀
🌍️ Copying public/ folder to out
💼 Copying static NextJS assets to out
💫 Setting up API endpoints as Netlify Functions in functions_bundle
💫 Setting up pages with getInitialProps as Netlify Functions in functions_bundle
💫 Setting up pages with getServerSideProps as Netlify Functions in functions_bundle
🔥 Copying pre-rendered pages with getStaticProps and JSON data to out
```

The Deploy details on Netlify show the following error:

```
    plugin error

    Plugin "@netlify/plugin-nextjs" internal error

    Error: ENOENT: no such file or directory, stat '.next/serverless/pages/jobs.js'

    In "onBuild" event in "@netlify/plugin-nextjs" from netlify.toml and package.json
    at Object.statSync (fs.js:1016:3)
    at Object.statSync (/opt/build/repo/node_modules/graceful-fs/polyfills.js:311:34)
    at statSync (/opt/build/repo/node_modules/fs-extra/lib/util/stat.js:10:52)
    at getStatsSync (/opt/build/repo/node_modules/fs-extra/lib/util/stat.js:24:19)
    at Object.checkPathsSync (/opt/build/repo/node_modules/fs-extra/lib/util/stat.js:49:33)
    at copySync (/opt/build/repo/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
    at setupNetlifyFunctionForPage (/opt/build/repo/node_modules/@netlify/plugin-nextjs/src/lib/helpers/setupNetlifyFunctionForPage.js:41:3)
    at async /opt/build/repo/node_modules/@netlify/plugin-nextjs/src/lib/pages/getStaticProps/setup.js:44:5
    at async asyncForEach (/opt/build/repo/node_modules/@netlify/plugin-nextjs/src/lib/helpers/asyncForEach.js:3:5)
    at async setup (/opt/build/repo/node_modules/@netlify/plugin-nextjs/src/lib/pages/getStaticProps/setup.js:20:3)

    Error properties:
    {
    errno: -2,
    syscall: 'stat',
    code: 'ENOENT',
    path: '.next/serverless/pages/jobs.js'
    }
```

I can confirm, that this file does not exist in the `.next/serverless` folder. Should it exist? There is no page called `pages/jobs` only `pages/jobs/index`. Is this supposed to be the same page?

`next build` runs fine, it's only during the netlify deployment that I get this error.

By debugging via `console.log()` I noticed that my build process never executes the callback (second parameter in this function) in https://github.com/netlify/netlify-plugin-nextjs/blob/70ee18449286b7fb07d9f07753103a88a18a4ece/src/lib/pages/getStaticProps/setup.js#L22-L49

**To Reproduce**

I'll be happy to provide a copy of the whole project, but I don't want to share it publicly here.

**Expected behavior**
The netlify plugin should finish the build successfully or at least throw a more descriptive error.

**Versions**
- Next.js: 10.2.0
- plugin (if installed at fixed version): 3.2.0

**If you're using the CLI to build**
 - OS: macOS 11
 - netlify/cli version: 3.23.2

**If you're using file-based installation**
- netlify.toml:

```
[build]
  command = "SITE_ROOT=$URL yarn build && yarn build:functions"
  functions = "functions_bundle"
  publish = "out"

[context.deploy-preview]
  command = "SITE_ROOT=$DEPLOY_PRIME_URL yarn build"
  functions = ""

[context.branch-deploy]
  command = "SITE_ROOT=$DEPLOY_PRIME_URL yarn build"
  functions = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"
```

Here is the complete build log:
```
11:21:14 AM: Waiting for other deploys from your team to complete
11:22:03 AM: Build ready to start
11:22:05 AM: build-image version: 7b53c5fc4445e3ec99d3949e5d1174a8c5be4f16
11:22:05 AM: build-image tag: v3.7.2
11:22:05 AM: buildbot version: a8df6d1263bb5bcc16f7b4ebb8e9a6cb904cfa8a
11:22:05 AM: Fetching cached dependencies
11:22:05 AM: Starting to download cache of 377.3MB
11:22:07 AM: Finished downloading cache in 2.339265643s
11:22:07 AM: Starting to extract cache
11:22:21 AM: Finished extracting cache in 13.182812203s
11:22:21 AM: Finished fetching cache in 15.622295015s
11:22:21 AM: Starting to prepare the repo for build
11:22:21 AM: Preparing Git Reference pull/92/head
11:22:24 AM: Different functions path detected, going to use the one specified in the Netlify configuration file: 'functions_bundle' versus '' in the Netlify UI
11:22:24 AM: Different build command detected, going to use the one specified in the Netlify configuration file: 'SITE_ROOT=$DEPLOY_PRIME_URL yarn build' versus 'npm run build' in the Netlify UI
11:22:24 AM: Starting build script
11:22:24 AM: Installing dependencies
11:22:24 AM: Python version set to 2.7
11:22:25 AM: Started restoring cached node version
11:22:28 AM: Finished restoring cached node version
11:22:28 AM: Attempting node version '12' from .nvmrc
11:22:28 AM: v12.22.1 is already installed.
11:22:29 AM: Now using node v12.22.1 (npm v6.14.12)
11:22:29 AM: Started restoring cached build plugins
11:22:29 AM: Finished restoring cached build plugins
11:22:29 AM: Attempting ruby version 2.3.6, read from environment
11:22:29 AM: Started restoring cached ruby version
11:22:30 AM: Finished restoring cached ruby version
11:22:31 AM: Using ruby version 2.3.6
11:22:32 AM: Successfully installed bundler-2.2.16
11:22:32 AM: 1 gem installed
11:22:32 AM: Using PHP version 5.6
11:22:32 AM: Started restoring cached yarn cache
11:22:32 AM: Finished restoring cached yarn cache
11:22:33 AM: Started restoring cached node modules
11:22:33 AM: Finished restoring cached node modules
11:22:33 AM: Installing NPM modules using Yarn version 1.3.2
11:22:33 AM: yarn install v1.3.2
11:22:33 AM: (node:1426) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
11:22:33 AM: [1/4] Resolving packages...
11:22:34 AM: [2/4] Fetching packages...
11:22:50 AM: info fsevents@2.3.2: The platform "linux" is incompatible with this module.
11:22:50 AM: info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
11:22:50 AM: info fsevents@1.2.13: The platform "linux" is incompatible with this module.
11:22:50 AM: info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
11:22:50 AM: [3/4] Linking dependencies...
11:22:50 AM: warning " > @emotion/react@11.1.5" has unmet peer dependency "@babel/core@^7.0.0".
11:22:50 AM: warning " > @emotion/styled@11.3.0" has unmet peer dependency "@babel/core@^7.0.0".
11:22:50 AM: warning "@emotion/styled > @emotion/babel-plugin@11.3.0" has unmet peer dependency "@babel/core@^7.0.0".
11:22:50 AM: warning "@emotion/styled > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.12.13" has unmet peer dependency "@babel/core@^7.0.0-0".
11:22:50 AM: warning " > next@10.2.0" has unmet peer dependency "fibers@>= 3.1.0".
11:22:50 AM: warning " > next@10.2.0" has unmet peer dependency "node-sass@^4.0.0 || ^5.0.0".
11:22:50 AM: warning " > next@10.2.0" has unmet peer dependency "sass@^1.3.0".
11:22:50 AM: warning "next > @next/react-refresh-utils@10.2.0" has unmet peer dependency "webpack@^4 || ^5".
11:22:50 AM: warning "@netlify/plugin-nextjs > @sls-next/lambda-at-edge > @zeit/node-file-trace > acorn-export-ns-from@0.1.0" has incorrect peer dependency "acorn@^6.0.1".
11:22:50 AM: warning "@netlify/plugin-nextjs > @sls-next/lambda-at-edge > @aws-sdk/client-s3 > @aws-sdk/middleware-retry > react-native-get-random-values@1.6.0" has unmet peer dependency "react-native@>=0.56".
11:22:50 AM: warning " > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
11:22:50 AM: warning " > url-loader@4.1.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
11:23:02 AM: [4/4] Building fresh packages...
11:23:03 AM: success Saved lockfile.
11:23:03 AM: Done in 29.71s.
11:23:03 AM: NPM modules installed using Yarn
11:23:03 AM: (node:1463) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
11:23:03 AM: Started restoring cached go cache
11:23:05 AM: Finished restoring cached go cache
11:23:05 AM: Installing Go version 1.10
11:23:05 AM: unset GOOS;
11:23:05 AM: unset GOARCH;
11:23:05 AM: export GOROOT='/opt/buildhome/.gimme_cache/versions/go1.10.linux.amd64';
11:23:05 AM: export PATH="/opt/buildhome/.gimme_cache/versions/go1.10.linux.amd64/bin:${PATH}";
11:23:05 AM: go version >&2;
11:23:05 AM: export GIMME_ENV='/opt/buildhome/.gimme_cache/env/go1.10.linux.amd64.env';
11:23:05 AM: go version go1.10 linux/amd64
11:23:05 AM: Installing missing commands
11:23:05 AM: Verify run directory
11:23:07 AM: ​
11:23:07 AM: ────────────────────────────────────────────────────────────────
11:23:07 AM:   Netlify Build                                                 
11:23:07 AM: ────────────────────────────────────────────────────────────────
11:23:07 AM: ​
11:23:07 AM: ❯ Version
11:23:07 AM:   @netlify/build 11.3.2
11:23:07 AM: ​
11:23:07 AM: ❯ Flags
11:23:07 AM:   deployId: 608a7a8aeaa0850007cc4a2a
11:23:07 AM: ​
11:23:07 AM: ❯ Current directory
11:23:07 AM:   /opt/build/repo
11:23:07 AM: ​
11:23:07 AM: ❯ Config file
11:23:07 AM:   /opt/build/repo/netlify.toml
11:23:07 AM: ​
11:23:07 AM: ❯ Context
11:23:07 AM:   deploy-preview
11:23:07 AM: ​
11:23:07 AM: ❯ Loading plugins
11:23:07 AM:    - @netlify/plugin-nextjs@3.1.0 from netlify.toml and package.json
11:23:07 AM: ​
11:23:07 AM: ────────────────────────────────────────────────────────────────
11:23:07 AM:   1. onPreBuild command from @netlify/plugin-nextjs             
11:23:07 AM: ────────────────────────────────────────────────────────────────
11:23:07 AM: ​
11:23:08 AM: info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
11:23:08 AM: ​
11:23:08 AM: (@netlify/plugin-nextjs onPreBuild completed in 655ms)
11:23:08 AM: ​
11:23:08 AM: ────────────────────────────────────────────────────────────────
11:23:08 AM:   2. build.command from netlify.toml                            
11:23:08 AM: ────────────────────────────────────────────────────────────────
11:23:08 AM: ​
11:23:08 AM: $ SITE_ROOT=$DEPLOY_PRIME_URL yarn build
11:23:08 AM: yarn run v1.3.2
11:23:08 AM: (node:1554) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
11:23:08 AM: $ next build
11:23:09 AM: info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
11:23:09 AM: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
11:23:09 AM: info  - Checking validity of types...
11:23:17 AM: info  - Creating an optimized production build...
11:23:42 AM: info  - Compiled successfully
11:23:42 AM: info  - Collecting page data...
11:23:42 AM: Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps`
11:23:42 AM: Read more: https://nextjs.org/docs/messages/opt-out-auto-static-optimization
11:23:44 AM: info  - Generating static pages (0/13)
11:23:47 AM: info  - Generating static pages (3/13)
11:23:48 AM: info  - Generating static pages (6/13)
11:23:48 AM: info  - Generating static pages (9/13)
11:23:48 AM: info  - Generating static pages (13/13)
11:23:48 AM: info  - Finalizing page optimization...
11:23:48 AM: Page                                                           Size     First Load JS
11:23:48 AM: ┌ ● /                                                          2.5 MB         2.97 MB
11:23:48 AM: ├   /_app                                                      0 B             432 kB
11:23:48 AM: ├ ● /[...slug]                                                 4.01 kB         436 kB
11:23:48 AM: ├   ├ /de/apps/offwhite/privacy
11:23:48 AM: ├   ├ /de/datenschutz
11:23:48 AM: ├   └ /de/impressum
11:23:48 AM: ├ λ /404                                                       2.99 kB         435 kB
11:23:48 AM: ├ ● /jobs                                                      4.71 kB         471 kB
11:23:48 AM: └ ● /jobs/[slug]                                               3.36 kB         470 kB
11:23:48 AM:     ├ /de/jobs/DevOpsEngineer
11:23:48 AM:     ├ /de/jobs/ReactNativeDeveloper
11:23:48 AM:     └ /de/jobs/TypeScriptDeveloper
11:23:48 AM: + First Load JS shared by all                                  432 kB
11:23:48 AM:   ├ chunks/48f63186d06fde451424f635cf5c89a73abbd8c5.5c53f2.js  15.5 kB
11:23:48 AM:   ├ chunks/54745ffe52962a21739a38f17e1969c4c6de94ec.ec1d4a.js  7.15 kB
11:23:48 AM:   ├ chunks/commons.abdf52.js                                   14.3 kB
11:23:48 AM:   ├ chunks/framework.6fff95.js                                 42.1 kB
11:23:48 AM:   ├ chunks/main.029299.js                                      6.94 kB
11:23:48 AM:   ├ chunks/pages/_app.1b24d3.js                                345 kB
11:23:48 AM:   └ chunks/webpack.50bee0.js                                   751 B
11:23:48 AM: λ  (Lambda)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
11:23:48 AM: ○  (Static)  automatically rendered as static HTML (uses no initial props)
11:23:48 AM: ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
11:23:48 AM:    (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
11:23:48 AM: Done in 40.05s.
11:23:48 AM: ​
11:23:48 AM: (build.command completed in 40.3s)
11:23:48 AM: ​
11:23:48 AM: ────────────────────────────────────────────────────────────────
11:23:48 AM:   3. onBuild command from @netlify/plugin-nextjs                
11:23:48 AM: ────────────────────────────────────────────────────────────────
11:23:48 AM: ​
11:23:48 AM: ** Running Next on Netlify package **
11:23:48 AM: 🚀 Next on Netlify 🚀
11:23:48 AM: 🌍️ Copying public/ folder to out
11:23:49 AM: info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
11:23:49 AM: 💼 Copying static NextJS assets to out
11:23:49 AM: 💫 Setting up API endpoints as Netlify Functions in functions_bundle
11:23:49 AM: 💫 Setting up pages with getInitialProps as Netlify Functions in functions_bundle
11:23:49 AM: 💫 Setting up pages with getServerSideProps as Netlify Functions in functions_bundle
11:23:49 AM: 🔥 Copying pre-rendered pages with getStaticProps and JSON data to out
11:52:05 AM: Build exceeded maximum allowed runtime
11:52:16 AM: Execution timed out after 29m51.521940896s
11:52:16 AM: Error running command: Command did not finish within the time limit
11:52:16 AM: Failing build: Failed to build site
11:52:16 AM: Finished processing build request in 30m10.851433585s
```

**Comment by lindsaylevine** [comment] 2021-05-03 18:27
@pReya hey! thanks for the detailed issue <3. how recently did you update to next 10.2.0? have you tried rolling that back (or any other suspect dependencies) to nail down at which version(s) it last worked? would be great insight for us over here if you knew for sure that your site worked on 10.x.x (whichever version it did). still, even with that insight, it'd be best for you to create a brand new, simple and deployable [public] repo that reproduces the issue. it could be as simple as only having the `jobs` page and whatever necessary deps. let me know!!!

**Comment by pReya** [comment] 2021-05-04 17:31
I'm trying to create a reproduction repo. I've found out, that upgrading my `@netlify/plugin-nextjs` from `3.0.0` to `3.2.2` creates the behavior described here. Going back to 3.0.0 fixes the problem for me. I'll see if I can narrow it even further down to a single version of the plugin.

**Comment by l3aconator** [comment] 2021-05-04 19:27
I don't know if this is related, but when upgrading to next `10.2.0` my site will not build because I keep running into OOM errors. I downgraded to `10.1.3` and the site builds just fine using `@netlify/plugin-nextjs` `3.2.1` and `3.2.3`

**Comment by lindsaylevine** [comment] 2021-05-04 19:41
@l3aconator i figured it'd be a 10.2.0 issue :/

i see @pReya is still using webpack 4 though so it's still hard for me to say exactly where your issues overlap.

if either of you (or anyone else) thinks this may still be partly a plugin problem, that simple repo with 10.2.0 would be necessary to debug 🙏

**Comment by l3aconator** [comment] 2021-05-04 20:00
@lindsaylevine No worries. I am getting really inconsistent results trying to isolate anyways. I was able to deploy just fine yesterday before upgrading `10.2.0` this morning. Now even with downgrading both `next` and `@netlify/plugin-nextjs` some deploys go through, some don't. Not sure why I am being hit with exit code `137` all of sudden.

**Comment by lindsaylevine** [comment] 2021-05-04 21:13
@l3aconator sheesh ok hm have you tried clearing cache and deploying? or trying a separate test site to see if results vary? :/ not sure if either will help but sorry you're having trouble!!!

**Comment by l3aconator** [comment] 2021-05-04 22:02
@lindsaylevine Great advice. 

- Cached build with `10.1.3` with latest netlify nextjs plugin. No bueno. Our build cache was 2.3gb! (Our marketing site is huge)
- Did a clean build on `10.1.3` webpack 5 with latest netlify nextjs plugin. All good. 
- Did a clean build on `10.2.0` webpack 5 (looks like they made a bunch of changes from the initial release) with latest netlify nextjs plugin. OOM error.

Thanks for all of your help and time today. I will keep `next` downgraded and see what changes down the road.

**Comment by lindsaylevine** [comment] 2021-05-16 00:59
@pReya have you narrowed this down at all for your specific site? would love to know for sure if this is a plugin-specific issue we need to resolve or if we should close it :)

**Comment by pReya** [comment] 2021-05-17 16:33
@lindsaylevine I narrowed it down to a specific version. My site works fine on 3.0.0. As soon as I upgrade to 3.0.1 the build process fails (as described above). Still trying to make a minimal reproduction of this problem. But it takes a while, because I need to remove so much stuff.

**Comment by lindsaylevine** [comment] 2021-05-19 10:03
@pReya ok let me know. if i had the bandwidth id try to reproduce myself but i dont 😕 as soon as i get that, i can try to figure out the root cause/necessary fix 🙏

**Comment by lindsaylevine** [comment] 2021-06-02 06:31
hey yall - i think we'll close this for the timebeing since tis been ~ 1 month since it was opened and 2 weeks since the last comment. if you end up still needing help and can provide a reproduction, pls feel free to comment again and we'll re-open!

**Closed by lindsaylevine** 2021-06-02 06:31 UTC
Labels: needs reproduction, priority: high, type: bug
