### ISSUE TITLE
[Bug]: Edge Middleware - TypeError: error sending request for url

### ISSUE THREAD

**Issue by JohnGemstone** [netlify/netlify-plugin-nextjs#1476] opened 2022-07-21 09:57 UTC
### Summary

Hey just came across an error with my site using Middleware on the Edge (the error redirects to a netlify error page away from the main site). I can't seem to reproduce but want to make a record of it in case it occurs again.

Edge Function log:
```
9:55:48 AM: [next_middleware] TypeError: error sending request for url (https://dev--[mysite].netlify.app/test): connection error: connection reset
    at async mainFetch (deno:ext/fetch/26_fetch.js:287:14)
    at async fetch (deno:ext/fetch/26_fetch.js:497:9)
    at async FunctionChain.fetchOrigin (netlify:bundle-combined:978:21)
    at async addMiddlewareHeaders (netlify:bundle-combined:18162:17)
    at async FunctionChain.runFunction (netlify:bundle-combined:1060:30)
    at async FunctionChain.run (netlify:bundle-combined:1047:26)
    at async handleRequest (netlify:bundle-combined:1097:26)
    at async Server.#respond (netlify:bundle-combined:351:24)
```

### Steps to reproduce

Unable to reproduce.

### Plugin version

4.12.2

### Middleware function

```js
import { NextResponse } from "next/server";

const TESTS = {
  homepage: {
    page: "/",
    cookie: "ab-homepage",
    buckets: ["original", "test"],
  },
};

export default function middleware(req) {
  const { pathname } = req.nextUrl;

  if (pathname === "/") {
    let test = TESTS["homepage"];

    let bucket = req.cookies.get(test.cookie);
    let reqHasBucket = new Boolean(bucket);

    if (!bucket || !test.buckets.includes(bucket)) {
      bucket = getBucket(test.buckets);
      reqHasBucket = false;
    }

    let url = req.nextUrl.clone();

    if (bucket !== "original") {
      url.pathname = `/${bucket}/`;
    }

    const res = NextResponse.rewrite(url);

    if (!reqHasBucket) {
      res.cookies.set(test.cookie, bucket);
    }

    return res;
  }
}


export const config = {
  matcher: ["/"],
};

export function getBucket(buckets) {
  let n = cryptoRandom() * 100;
  let percentage = 100 / buckets.length;
  return (
    buckets.find(() => {
      n -= percentage;
      return n <= 0;
    }) ?? buckets[0]
  );
}

function cryptoRandom() {
  return crypto.getRandomValues(new Uint32Array(1))[0] / (0xffffffff + 1);
}

```

**Comment by ascorbic** [comment] 2022-07-21 10:14
Thank you for the report. If you cannot reproduce it, this seems like it was a transient network error, connecting to the origin. I'm going to close this for now, but please do report again if it recurs.

**Closed by ascorbic** 2022-07-21 10:14 UTC
Labels: type: bug
