### ISSUE TITLE
[Bug]: Trailing slash not working

### ISSUE THREAD

**Issue by scajal** [netlify/netlify-plugin-nextjs#1329] opened 2022-04-27 12:58 UTC
### Summary

The option `trailingSlash: true` is not working when deploying a site.
The site also has `Pretty URLs` option activated in the deploy settings.
Some links work with the slash (but have both versions, which is bad for SEO).

The only pages that are working with trailing slash are server side pages.

### Steps to reproduce

1. Access https://cerulean-travesseiro-e6b413.netlify.app/ and visit the different links

### A link to a reproduction repository

https://github.com/scajal/netlify-test

### Plugin version

4.7.0

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```
/** @type {import('next').NextConfig} */
const nextConfig = {
	/** @see https://nextjs.org/docs/api-reference/next.config.js/react-strict-mode */
	reactStrictMode: true,

	/** @see https://nextjs.org/docs/api-reference/next.config.js/trailing-slash */
	trailingSlash: true,
};

module.exports = nextConfig;
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by scajal** [comment] 2022-05-03 15:41
bump

**Comment by scajal** [comment] 2022-05-04 14:00
Up

**Comment by scajal** [comment] 2022-05-16 14:27
Up

**Comment by scajal** [comment] 2022-05-23 12:15
Up

**Comment by shubhendusaurabh** [comment] 2022-06-12 19:08
I'm facing the same problem in netlify, works correctly in vercel.

directly going to `/path/` results in 301 redirection to `/path`. however client side navigation works correctly.

i was able to stop 301 redirect by enabling pretty urls in asset optimization but the same page is duplicated in 2 different urls i.e. `/path` and `/path/` which is bad for SEO.

**Comment by ericapisani** [comment] 2022-06-16 13:20
Hi all!

First off, thanks @scajal for the initial issue submission and the repro and thanks @gnevin and @shubhendusaurabh for the additional information.

Unfortunately this is not a bug with the plugin but is behaviour resulting from our logic on the Netlify CDN aimed at keeping site performance high by maximizing the cache hit rate. I've raised this issue with the related team and confirmed that this behaviour is not configurable, but have asked about further investigation into ways to mitigate or address the SEO issues that are being caused as a result of the page duplication that's been mentioned here.

I had investigated trying to create an edge function that would've supported this behaviour as a workaround, but unfortunately that kind of redirect causes an infinite loop because the resulting paths are essentially the same.

Related Netlify docs for those interested in reading a bit more can be found [here](https://docs.netlify.com/routing/redirects/redirect-options/#trailing-slash)

Because this is an issue resulting from behaviour with the CDN and not the plugin, this bug will be closed as 'won't fix/do', but please don't hesitate to ask any follow up questions here.

**Closed** 2022-06-16 17:38 UTC
Labels: type: bug

**Comment by ascorbic** [comment] 2022-06-17 09:56
I've made a quick demo of using edge functions to strip the trailing slashes. I will add an equivalent to add the slashes. It works around the different ways the CDN defines the canonical URL. We will add this to the plugin so it works by default according to the next config, but for now you can add it manually.

https://github.com/ascorbic/slash-edge

**Comment by scajal** [comment] 2022-06-17 12:40
Hi @ascorbic, your solution is not working for me, it throws ERR_TOO_MANY_REDIRECTS in the browser.

**Comment by ascorbic** [comment] 2022-06-17 13:09
@scajal can you try with an updated version?

**Comment by grahamd711** [comment] 2023-05-17 19:49
thank you @ascorbic ! your solution works for our Next.js app on Netlify

**Comment by samlogan** [comment] 2024-03-12 04:44
Hey @ascorbic, I'm unsure if there's been an update on Netlify's side, but I am getting the redirect issue with top level pages; I also see this on your demo.

<img width="986" alt="CleanShot 2024-03-12 at 15 42 44@2x" src="https://github.com/netlify/next-runtime/assets/8562933/cc70ac72-606e-485e-b316-501618fb4b36">

**Comment by samlogan** [comment] 2024-03-12 04:46
Hey, @ascorbic, I'm unsure if there's been an update on Netlify's side, but I am getting the redirect issue with top-level pages; I also see this on your demo.

<img width="1036" alt="CleanShot 2024-03-12 at 15 46 08@2x" src="https://github.com/netlify/next-runtime/assets/8562933/25c1c27b-9b89-4b41-be13-0894b0e9a5fa">
