### ISSUE TITLE
trailingSlash: true is not working on Netlify

### ISSUE THREAD

**Issue by klattiation** [netlify/netlify-plugin-nextjs#256] opened 2021-05-02 22:58 UTC
Hi, first of all thanks for the great work you're putting into this plugin.

**Describe the bug**
We have a Next.js site on Netlify with static and server-rendered pages. We have links like https://example.com/locations/berlin and we would like to have them to always end with a trailing slash like https://example.com/locations/berlin/. Everything works fine locally, but when we deploy it to Netlify the pages are always redirected to the url without trailing slash, like https://example.com/locations/berlin with status code 301. We already enabled [Pretty URLs](https://docs.netlify.com/routing/redirects/redirect-options/#trailing-slash) in the Netlify Build Settings but that makes no difference.

When I understand it correctly, with `trailingSlash: true`, Next.js should create the static pages like that:
`https://example.com/locations/berlin/index.html`

But instead it creates pages like that:
 `https://example.com/locations/berlin.html`

**To Reproduce**
```js
// next.config.js
module.exports = {
    target: "serverless",
    trailingSlash: true,
};
```

For our static pages, we use a `pages/[...slug].js` file that exports our static paths with `fallback: false`.

Since we use server rendered pages too, we can't use `next export`.

**Expected behavior**
- Pages without trailing slash are redirected with status code 301 to the url with a trailing slash
- Pages with trailing slash are loaded directly with status code 200

**Versions**
- next: 10.2.0
- @netlify/plugin-nextjs: 3.2.0

**If you're using file-based installation**

```toml
# netlify.toml

[build]
    command = "yarn build"

[[plugins]]
    package = "@netlify/plugin-nextjs"
```

```js
// package.json

{
  ...
  "scripts": {
    "build": "next build",
    ...
  }
}
```

**Comment by lindsaylevine** [comment] 2021-05-03 18:22
@klattiation hello! i'm sorry you're running into this :(. this is unfortunately an edge case on our platform and i think the first we've ever heard of it in the next on netlify initiative.

>When I understand it correctly, with trailingSlash: true, Next.js should create the static pages like that:
https://example.com/locations/berlin/index.html

>But instead it creates pages like that:
https://example.com/locations/berlin.html

i'm not sure about that. i haven't built a next app with trailingSlash but i'm not sure why that'd be the case. anyways, will have to dig into this later when it can be prioritized :/

**Comment by klattiation** [comment] 2021-05-04 19:14
@lindsaylevine Ok, thank you!

**Comment by osseonews** [comment] 2021-05-17 20:26
This is a major bug actually, and I'm surprised nobody else reporting it. We now have to redo all our links, because  putting "trailingSlash: true" into next.config won't do a thing on Netlify. What is supposed to happen is example.com/hello should redirect to example.com/hello/  - but this does not happen on Netlify even if you set up Pretty URL's. Both URL's are available no matter what you do. The only solution is to NOT use "trailingSlash: true" so that by default Netlify will redirect all "trailing slash" to non-trailing slash pages. This is of course very annoying to fix, and appears to be against common practice now, to end all URL's with a slash. Basically, you can only have a NextJs site on netlify if you opt to have URL's like this: example.com/hello

**Comment by dekked** [comment] 2021-06-19 00:04
It doesn't seem like this should be treated as low priority.

There is a [post on the Netlify forum](https://answers.netlify.com/t/nextjs-trailing-slashes/38693/6) and another one [on StackOverflow](https://stackoverflow.com/q/67371203) because of this issue.

I am about to migrate to Netlify and I would really like to avoid the ton of 301 that this bug will require me to have.

**Comment by hughrawlinson** [comment] 2021-06-23 12:56
I am also encountering this issue. It breaks netlify-cms :cry:

**Comment by lunelson** [comment] 2021-08-03 09:54
Agreed, this is a major issue. 

We have previously deployed Gatsby and Docusaurus, where we took alot of of pains to make our internal URLs consistently be written with trailing slashes. In fact we had to align on trailing slashes because Netlify didn't allow us to create the necessary redirects ourselves. Rather, the `Pretty URLs` feature was the only way to create the redirects, and since both Gatsby and Docusaurus build to `/foo/bar/index.html` files, the result was trailing slashes on all paths. 

The fact that Next.js on Netlify now reverses this behaviour is a show-stopper for existings sites and pages that we want to transition to Next.js, it will cause unmanageable inconsistencies and damages to search ranking

**Comment by lindsaylevine** [comment] 2021-08-03 11:24
hi all! just want to say that we hear you and so i updated the label to reflect that. we appreciate your patience because this issue is a tricky one, and our bandwidth as a team has been stretched thinner than it used to be :'(. hang tight because we're trying to move off target serverless this year and that could possibly simplify this feature.

**Comment by lindsaylevine** [comment] 2021-10-02 07:10
hello all! per my previous comment (gosh that was two months ago???) -- we are approaching completion of our plugin rewrite, and with testing so far, we believe trailingSlash is supported in the rewrite. we'll circle back to this issue when we can offer you a beta to test and/or when the rewrite has officially shipped. thanks so much for your patience!!!

**Comment by lqze** [comment] 2021-10-03 23:43
Simply a kudos to @lindsaylevine ! Such a thoughtful maintainer and genuinely show that you care. Nice work 👍

**Comment by ascorbic** [comment] 2021-11-01 11:17
Fixed in v4

**Closed by ascorbic** 2021-11-01 11:17 UTC
Labels: type: bug, priority: high, rewrite candidate, fixed in upcoming release

**Comment by scajal** [comment] 2022-04-25 15:42
I'm still facing this issue after deploying.

**Comment by ascorbic** [comment] 2022-04-27 09:05
@scajal can you open a new issue, with the details requested in the template. The cause is likely to be different, because the plugin is effectively completely different since this was reported.

**Comment by scajal** [comment] 2022-04-27 12:59
@ascorbic issue created at [https://github.com/netlify/netlify-plugin-nextjs/issues/1329](#1329)
