### ISSUE TITLE
Static files are not correctly served with `netlify dev`

### ISSUE THREAD

**Issue by guhur** [netlify/netlify-plugin-nextjs#214] opened 2021-04-11 16:05 UTC
**Describe the bug**
When I run `netlify build` and then an instance of `netlify dev`, the static files are not served. The navigator reports a bunch of 404 errors.
It happens for pages that contain a `getServerSideProps` and with `target: experimental-serverless-trace`.

**To Reproduce**

1. Clone `https://github.com/guhur/mre-nextjs-netlify-subfolder`
2. Install the repo and launch the application:
```bash
npm install
netlify init
netlify build
netlify dev
```
3. Open the navigator on localhost:8888
3. See the error: no CSS is loaded.

**Versions**
- Next.js: 10.1.3
- plugin (if installed at fixed version): see https://github.com/guhur/mre-nextjs-netlify-subfolder/blob/main/package-lock.json

**If you're using the CLI to build**
 - OS: Ubuntu 20.04
 - netlify/cli version: 3.17.0

**If you're using file-based installation**
- netlify.toml:

```toml
[build]
  command = "npm run build"
  publish = "out"
```

**Comment by lindsaylevine** [comment] 2021-04-12 08:36
@guhur thanks so much for the detailed issue and repro <3 sorry for low priority label, we'll try to get to this when we can. lots of stuff going on though 🥵

**Comment by ascorbic** [comment] 2021-07-23 11:56
This is possibly caused by https://github.com/netlify/cli/issues/2990

**Comment by ascorbic** [comment] 2021-11-01 11:17
Fixed in v4

**Closed by ascorbic** 2021-11-01 11:17 UTC
Labels: type: bug, priority: low, fixed in upcoming release
