### ISSUE TITLE
[Bug]: Local netlify build results in 404 while fetching static JS & CSS files, but cloud deploy works 

### ISSUE THREAD

**Issue by icy-meteor** [netlify/netlify-plugin-nextjs#969] opened 2021-12-12 04:14 UTC
### Steps to reproduce

Cloud build: 
1. Go to the repro repo link and click "Deploy to netlify".
2. Proceed with all defaults and deploy the project.
3. The site should become live and look something like https://cloud-build-nextjs.netlify.app/

Local Build:
1. Make sure you have netlify-cli installed. Install using `npm i -g netlify-cli@latest`
2. Clone the repro repo and execute `netlify build` in the root directory.
3. Execute `netlify deploy` in the root directory.
4. The site should become live and look something like https://local-build-nextjs.netlify.app/

Points to note:
1. Check the network requests tab for the local build website and you will notice multiple 404 requests for all the resources being fetched from _next directory.
![image](https://user-images.githubusercontent.com/22114682/145699937-198e280a-deed-47fe-b9e3-cb0dadb0c888.png)

2. I checked the files generated for the local build and it looks like the requests are looking in the _next folder but those resources are actually present within the .next folder. The _next folder has empty folders inside it after the local build.
![image](https://user-images.githubusercontent.com/22114682/145699967-a83b6c19-3bcb-492e-9ef6-ff8790b698c8.png)

 

### A link to a reproduction repository

https://github.com/icy-meteor/next-netlify-starter

### Plugin version

4.0.0-beta.12

### More information about your build

- [x] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your `netlify.toml` file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
```

</details>

**Comment by icy-meteor** [comment] 2021-12-12 04:17
I was going through some previous github issues and apparently the command `netlify deploy --build` seems to do the trick. Draft site deployed using the command - https://61b5775d5ea88fcc25645b2f--local-build-nextjs.netlify.app/

Link: https://github.com/netlify/netlify-plugin-nextjs/issues/953#issuecomment-990056142

**Comment by ascorbic** [comment] 2021-12-12 07:08
Hi,
The issue here is that the image server uses native modules (sharp, specifically) and if you build locally, it builds the sharp module for Mac OS. When you then deploy it, that means it sends the Mac binaries, but the functions run on Linux when deployed. This is just a limitation of how npm works, There are a few ways around this (apart from building on Netlify or other Linux CI environment): you can build locally in a Docker container or some kind of virtualisation environment. You could also [pass it the flags to install the Linux version](https://sharp.pixelplumbing.com/install#cross-platform) instead when installing on your Mac, but thsi will mean you won;t be able to run it on your Mac.

The final option is to use a separate image service such as imgix or Cloudinary, which are supproted by Next.js.

**Comment by icy-meteor** [comment] 2021-12-12 07:18
> Hi, The issue here is that the image server uses native modules (sharp, specifically) and if you build locally, it builds the sharp module for Mac OS. When you then deploy it, that means it sends the Mac binaries, but the functions run on Linux when deployed. This is just a limitation of how npm works, There are a few ways around this (apart from building on Netlify or other Linux CI environment): you can build locally in a Docker container or some kind of virtualisation environment. You could also [pass it the flags to install the Linux version](https://sharp.pixelplumbing.com/install#cross-platform) instead when installing on your Mac, but thsi will mean you won;t be able to run it on your Mac.
> 
> The final option is to use a separate image service such as imgix or Cloudinary, which are supproted by Next.js.

Ah, yes. I get it now. Thanks for your response :)
Besides that, I am not sure why the 2 separate commands didn't work as opposed to `netlify deploy --build` but it gets the job done 👍🏼

**Comment by icy-meteor** [comment] 2021-12-12 08:00
@ascorbic I had a doubt regarding the image optimization that netlify does. I have noticed there is a slight delay in loading the image when a user hits the first time but subsequent hits load up instantly. I suppose there's some kind of caching going on.
Does netlify optimize and cache an image at the CDN level or does it optimize the image at every request? Does it mean that only the first request to that image in a particular CDN location will notice a delay?

**Comment by ascorbic** [comment] 2021-12-12 08:37
It's both. The first request optimises it and stores it in a global cache so future requests don't need to process it. Each edge node also caches it locally when it's first requested.

**Comment by ascorbic** [comment] 2021-12-12 08:53
I've opened an issue on the CLI to better handle the `deploy --build` situation. I'll close this now because it's a duplicate of the other issue. https://github.com/netlify/cli/issues/3792

**Closed by ascorbic** 2021-12-12 08:53 UTC
Labels: type: bug
