### ISSUE TITLE
Trying to use "unstable-functions-support" and getting error "ReferenceError: fs is not defined"

### ISSUE THREAD

**Issue by joelvarty** [netlify/netlify-plugin-nextjs#201] opened 2021-04-06 19:23 UTC
Trying to get unstable functions support to work with Agility CMS's NextJS implementation for Preview mode and ISR. 
This is the repo (trying to build a specific branch): https://github.com/agility/agility-nextjs-blog-ts/tree/animations 

Latest deploy details:  
https://app.netlify.com/sites/kind-perlman-97c6e9/deploys/606cb374152bea0008446d6a

Here's the deploy summary from netlify: 
```
Plugin "@netlify/plugin-nextjs" internal error

ReferenceError: fs is not defined

In "onPostBuild" event in "@netlify/plugin-nextjs" from netlify.toml and package.json
at /opt/build/repo/node_modules/@netlify/plugin-nextjs/helpers/copyUnstableIncludedDirs.js:15:7
at Array.forEach ()
at copyUnstableIncludedDirs (/opt/build/repo/node_modules/@netlify/plugin-nextjs/helpers/copyUnstableIncludedDirs.js:14:17)
at onPostBuild (/opt/build/repo/node_modules/@netlify/plugin-nextjs/index.js:69:5)
at async Object.run (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/run.js:18:3)
at async handleEvent (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/main.js:36:38)
at async process. (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/ipc.js:103:16)
```

**If you're using file-based installation**
- netlify.toml:
```
[build]
  command   = "yarn build"
  publish = "out_publish"
  functions = "out_functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
```

- next.config.js
```
module.exports = {
	target: "serverless",
	future: {
		webpack5: false,
	},
	unstableNetlifyFunctionsSupport: {
		'pages/[...slug].tsx': {
			includeDirs: ['./.next/cache/agility']
		},
		'pages/index.tsx': {
			includeDirs: ['./.next/cache/agility']
		}
	}
}
```

Let me know if you need any other details!

**Comment by joelvarty** [comment] 2021-04-06 19:26
In case it helps, here's my package.json

```
{
  "name": "agility-nextjs-blog",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "predev": "agility-next sync",
    "dev": "next dev",
    "prebuild": "agility-next prebuild",
    "build": "next build",
    "export": "next export",
    "postbuild": "agility-next postbuild",
    "start": "next start",
    "cms-pull": "agility-next sync",
    "cms-clean": "agility-next clean"
  },
  "dependencies": {
    "@agility/content-sync": "^1.0.1",
    "@netlify/plugin-nextjs": "git://github.com/netlify/netlify-plugin-nextjs.git#unstable-functions-support",
    "framer-motion": "^4.0.0",
    "next": "^10.0.9",
    "react": "17.0.1",
    "react-dom": "17.0.1"
  },
  "devDependencies": {
    "@agility/nextjs": "^0.1.8",
    "@tailwindcss/jit": "^0.1.1",
    "@tailwindcss/typography": "^0.4.0",
    "@types/node": "^14.14.35",
    "@types/react": "^17.0.3",
    "autoprefixer": "^10.2.5",
    "postcss": "^8.2.8",
    "tailwindcss": "^2.0.3",
    "truncate-html": "^1.0.3",
    "typescript": "^4.2.3"
  }
}
```

**Comment by lindsaylevine** [comment] 2021-04-06 21:04
@joelvarty hey! we just discussed this on twitter but for anyone reading through issues - this is due to a missing require in the branch and is currently in the process of being fixed along with a refactor. i'm going to close for now since the issue is resolved locally in the refactor and will be released soon when the temporary unstable solution gets merged into main. 🙏

**Closed by lindsaylevine** 2021-04-06 21:05 UTC
