### ISSUE TITLE
plugin mistake my site not being a next.js site

### ISSUE THREAD

**Issue by MeztliRA** [netlify/netlify-plugin-nextjs#228] opened 2021-04-20 09:21 UTC
**Describe the bug**
my problem is quite similar to #219 but im using yarn with pnp, i tried setting the yarn version to berry, using next build and then next export,  just using next build, un gitignoring .yarn/cache, and everything else i can think about how to fix this

**To Reproduce**
1. Create a next.js project using yarn with pnp
2. try to deploy site on netlify
3. plugin says its not a next.js site and told me to run yarn next on the repo

**Expected behavior**
plugin work and my site get deployed

**Versions**
- Next.js: v10.1.3

**Comment by lindsaylevine** [comment] 2021-04-20 20:08
@MeztliRA hello! apologies you're running into issues with PnP :( i believe this is a duplicate of https://github.com/netlify/netlify-plugin-nextjs/issues/169 so i'm going to close this, but if you believe it's not, feel free to re-open!!!

**Closed by lindsaylevine** 2021-04-20 20:08 UTC
Labels: duplicate
