### ISSUE TITLE
Dynamic routes not working well If an error page is added.

### ISSUE THREAD

**Issue by Doaa-Ismael** [netlify/netlify-plugin-nextjs#290] opened 2021-05-11 01:54 UTC
correct me if I am wrong, all static files should be served from functions directly anything else should go through my _app, right?

I deployed a serverless NEXTJS application that implements SSR ( server-side rendering ), and it has some dynamic routes.
It works fine until I press on a link that links to a page that had a dynamic route… for example `branches/[id]`
It sends a request to get the static js file or the chunk js file needed to serve the page … but instead of getting the file directly because it’s a static js file, it goes through my `_app`! which makes a redirection to the default locale.

static file URL example
`https://example.app/_next/static/chunks/pages/branches/%5Bid%5D-91768ff65c2a79ad38ee.js `when it goes through _app it get redirected to `https://example.app/en/_next/static/chunks/pages/branches/%5Bid%5D-91768ff65c2a79ad38ee.js `  which doesn't exist so, it sends a 404 page.

environment:
node version: 14.15.1
next version: 10.0.9

and I am using new “@netlify/plugin-nextjs” plugin to deploy

PLEASE HELPPPPP

**Comment by lindsaylevine** [comment] 2021-05-11 15:25
@Doaa-Ismael hello! happy to help! can you pls open a repo that reproduces this issue? 🙏  that's the fastest way for me to figure out your issue!

**Comment by lindsaylevine** [comment] 2021-05-16 00:56
@Doaa-Ismael hey! are you able to give us a repo that reproduces this issue? otherwise we'll close the issue until we have a direct way to help!

**Comment by Doaa-Ismael** [comment] 2021-05-16 02:22
@lindsaylevine Thank you for your help. I am trying to reproduce it but so far no luck.
You can close it until I can reproduce it.

**Comment by lindsaylevine** [comment] 2021-05-16 04:47
ok! let us know!!

**Comment by AhmedMedhatHabib** [comment] 2021-05-17 09:50
@lindsaylevine Hi, 
I have the same issue it actually happens after adding a custom 404 page and add it to the redirects in `netlify.toml` 

So adding the following lines cause that problem and removing them fixes it but I can't use my 404 page
`
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_404"
  status = 404
  `

**Comment by lindsaylevine** [comment] 2021-05-17 11:14
hey! same thing i told doaa - if you want us to help please provide a repo that reproduces your issue 🙏🏼🙏🏼

**Comment by Doaa-Ismael** [comment] 2021-05-18 21:51
@lindsaylevine Hey, Thanks for your help.
Here is a [repo](https://github.com/Doaa-Ismael/NextAppWithDynamicRoutes) that produces the issue,
And this is a deployed [link](https://nervous-wright-bd2aea.netlify.app/)

The problem is that when you add a redirection rule specifically for 404 serverless function, all static js files with a dynamic route either served from the 404 function or return 200 status with no response, and after that application reloads.

and if you tried to access the static js file from URL directly it will respond correctly with the right js file.
here is an example of a static chunk file: 
https://nervous-wright-bd2aea.netlify.app/_next/static/chunks/pages/numbers/%5Bid%5D-ab60cba0bf0a845a1df0.js

and this is the log of the 404 function

<img width="1196" alt="Screen Shot 2021-05-18 at 11 46 48 PM" src="https://user-images.githubusercontent.com/24235866/118727803-aa018000-b833-11eb-9511-78f420f1a92c.png">


Note: please try it from incognito browser, and if you tried to access the URL directly everything will work correctly as it get cached I think.

**Comment by lindsaylevine** [comment] 2021-05-19 10:00
@Doaa-Ismael hello! i forked and deployed and went directly to my site in an incognito window. then i went to /numbers. then i clicked on multiple different /numbers/:id. here's my network tab. i see no issues here so i'm confused D:. what am i missing? 

<img width="837" alt="Screen Shot 2021-05-19 at 5 58 23 AM" src="https://user-images.githubusercontent.com/57350178/118794189-527d0780-b867-11eb-8cdc-4b96abff59b7.png">
<img width="837" alt="Screen Shot 2021-05-19 at 5 58 27 AM" src="https://user-images.githubusercontent.com/57350178/118794191-53159e00-b867-11eb-89ad-fe0e0b0d7027.png">

**Comment by Doaa-Ismael** [comment] 2021-05-19 11:25
@lindsaylevine Hi,
I as I told you when you try to access any number/90 for example, the application should get a js file for this route ... say js file is located at app/_next/static/chunks/pages/numbers/%5Bid%5D-ab60cba0bf0a845a1df0.js
the response either 200 status with no actual response,

<img width="1436" alt="Screen Shot 2021-05-19 at 1 20 48 PM" src="https://user-images.githubusercontent.com/24235866/118804752-5fb8e700-b8a5-11eb-9b0e-9a8d29fdc9fe.png">

 or the custom 404 page (HTML) 
 <img width="1439" alt="Screen Shot 2021-05-19 at 1 21 37 PM" src="https://user-images.githubusercontent.com/24235866/118804805-6d6e6c80-b8a5-11eb-9d36-d2586f6e7b2a.png">

if it return HTML, you will find an error in the console `Uncaught SyntaxError: Unexpected token '<'`


after either response .. the application reloads and renders the correct page .. you see it get _builManifest file and _ssgManifest again every time you click on any number!

**Comment by lindsaylevine** [comment] 2021-05-20 23:38
ok i think i mostly understand what's going on now. thanks for your patience and explaining it thoroughly!!! 🙏  i think i got mixed up because in the original post the issue seemed to be primarily that the chunk req url had a [default] locale in it, but now the primary issue seems to just be this /* redirect to the 404 func. i'm not sure what the solution is at the moment but obv i'll dig into it deeper when i can and let you know!

**Comment by Doaa-Ismael** [comment] 2021-05-20 23:51
@lindsaylevine Thank you, you are right, the issue discreption is misleading so I was thinking of updating it 🙏.

**Comment by lindsaylevine** [comment] 2021-05-21 03:36
no worries! i think i may know what's going on.. it just occurred to me randomly lol. but wanna check for both of you - is the real/underlying issue really that you need the redirect to be able to use your custom 404?

**Comment by Doaa-Ismael** [comment] 2021-05-21 23:23
Yes! We need the redirect to be able to use our custom 404 and, without misbehaviours in the other files.

**Comment by lindsaylevine** [comment] 2021-05-22 11:51
@Doaa-Ismael - hey! i think this is a bug with using getInitialProps on your _app component. this causes your otherwise static 404.js to not get prerendered as html. not sure why the framework does this, but this is the root of the issue i believe. i can play around with trying to support this use case, but in the meantime, can you try working that out of your site? my understanding is that getInitialProps is no longer recommended as of next 9.3.

**Comment by lindsaylevine** [comment] 2021-05-22 12:19
relevant comment i think: https://github.com/vercel/next.js/discussions/10874#discussioncomment-1085

**Comment by lindsaylevine** [comment] 2021-06-02 06:30
hey @Doaa-Ismael - we'll close this since we haven't heard from you but let us know if you're still having an issue!

**Comment by Doaa-Ismael** [comment] 2021-07-08 11:11
@lindsaylevine  sorry for not being active.
The problem happens whenever I add an error page ( not html ), so I guess getInitalProps has nothing to do with this issue. Currently, my application use `getInitalProps` in `_app`, and I opted out of static site generation and I can't use `getSeverSideProps` in `_app` as it not supported by Next currently.

So could you please help me figure out how to solve this?

**Comment by lindsaylevine** [comment] 2021-07-08 11:20
hey @Doaa-Ismael i got an email that you left a new comment but i don't see it here. perhaps you deleted?

**Comment by Doaa-Ismael** [comment] 2021-07-08 13:04
@lindsaylevine Yes I wrote a comment and I deleted it and sorry for not being active.

The problem happens whenever I add an error page ( not html ), so I guess getInitalProps has nothing to do with this issue.

When I try to access a dynamic route page like `numbers/12` it should fetch the javascaript static file needed to show this page, so in the network tap I see the request to `https://numbers-next-app.netlify.app/_next/static/chunks/pages/numbers/%5Bid%5D-ab60cba0bf0a845a1df0.js`
the response is nothing "Faild to load response" and the application reload.

If you tired to access this route directly `https://numbers-next-app.netlify.app/_next/static/chunks/pages/numbers/%5Bid%5D-ab60cba0bf0a845a1df0.js` sometime the response is the correct javascript file  and most of the other times  it responds with the not found page.

I don't know if the problem that the route should be` https://numbers-next-app.netlify.app/_next/static/chunks/pages/numbers/[id]-ab60cba0bf0a845a1df0.js` with right brackets symbols "[]" between the "id" 

So could you please help me figure out how to solve this?

**Comment by ascorbic** [comment] 2021-07-08 14:01
Hi @Doaa-Ismael ,
I can't reproduce the problem. Could you talk us through the exact steps. When I visit your site and navigate to the numbers page I get no errors. Do you have any extensions enabled?
![image](https://user-images.githubusercontent.com/213306/124935113-40b11880-dffd-11eb-80b2-73cb28aba2b0.png)

**Comment by Doaa-Ismael** [comment] 2021-07-08 14:41
Hi @ascorbic 
the steps are:
1) go to https://numbers-next-app.netlify.app/
2) click on "go to numbers"
3) click on "go to any number"
You will see that the application reloads! it should get a js file and render the page without reloading.

**Comment by ascorbic** [comment] 2021-07-09 16:31
This is fascinating. The problem is that the page is requesting `https://numbers-next-app.netlify.app/_next/static/chunks/pages/numbers/%5Bid%5D-ab60cba0bf0a845a1df0.js`, which is failing, but when the page reloads it loads `https://numbers-next-app.netlify.app/_next/static/chunks/pages/numbers/%5Bid%5D-ab60cba0bf0a845a1df0.js` instead, which works. I think this is a bug in our server, but I'll have to talk to our backend team.

**Comment by Doaa-Ismael** [comment] 2021-07-11 14:56
Hey @ascorbic.
actually this url ` https://numbers-next-app.netlify.app/_next/static/chunks/pages/numbers/%5Bid%5D-ab60cba0bf0a845a1df0.j` 
don't work the first time and after that, it works fine and the js file gets returned!

**Comment by ascorbic** [comment] 2021-07-15 07:05
Hi @Doaa-Ismael,
This was indeed a bug in our server with the handling of URL-encoded paths, which has now been fixed. Your repro seems to work now. Thanks for the detailed report!

**Closed by ascorbic** 2021-07-15 07:05 UTC
Labels: priority: high, type: bug
