### ISSUE TITLE
Build fails - Cannot find module 'konva'

### ISSUE THREAD

**Issue by justincavery** [netlify/netlify-plugin-nextjs#571] opened 2021-07-30 19:11 UTC
**Describe the bug**
Build is failing when using the netlfiy NextJS plugin.

**To Reproduce**
Deploy and we get the following message.

```
5:20:10 PM:   A Netlify Function failed to require one of its dependencies.
5:20:10 PM:   Please make sure it is present in the site's top-level "package.json".
​
5:20:10 PM:   In file "/opt/build/repo/netlify/functions/next_migrate/next_migrate.js"
5:20:10 PM:   Cannot find module 'konva'
5:20:10 PM:   Require stack:
5:20:10 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/node_dependencies/resolve.js
5:20:10 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/node_dependencies/index.js
5:20:10 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/main.js
5:20:10 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins_core/functions/utils.js
5:20:10 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins_core/functions/index.js
5:20:10 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/commands/get.js
5:20:10 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/core/main.js
5:20:10 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/core/bin.js
```

**Expected behavior**
Expect this to build as per usual.

**Versions**
- Next.js: Latest
- plugin (if installed at fixed version): Latest

**Comment by lindsaylevine** [comment] 2021-07-30 19:57
@justincavery hey! to start, before asking you for a reproduction, could you try:

setting your `target` value in `next.config.js` to `experimental-serverless-trace`?

and/or

setting your node_bundler in your netlify.toml to esbuild? see https://docs.netlify.com/configure-builds/file-based-configuration/#functions

**Comment by lindsaylevine** [comment] 2021-07-30 19:57
though just looked again, this isn't a runtime error...

**Comment by lindsaylevine** [comment] 2021-07-30 19:57
is `konva` installed in your package.json? are you requiring it in your migrate page or api function?

**Comment by quagliero** [comment] 2021-07-30 20:03
@lindsaylevine hi! No it's not a dependency of ours. Builds just started failing for us and no changes had been made to package.json

I managed to get the functions section building after adding a further 9 devDependencies that the build process claimed it needed.. but then we got:

```bash
:32 PM: ────────────────────────────────────────────────────────────────
8:50:32 PM:   6. Deploy site                                                
8:50:32 PM: ────────────────────────────────────────────────────────────────
8:50:32 PM: ​
8:50:32 PM: Starting to deploy site from 'out'
8:50:35 PM: Creating deploy tree 
8:50:35 PM: Creating deploy upload records
8:50:35 PM: 49 new files to upload
8:50:35 PM: 2 new functions to upload
8:50:44 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
8:50:47 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
8:50:50 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
8:50:52 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
8:50:55 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
8:50:59 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
8:51:05 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
8:51:13 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
8:51:19 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
8:51:34 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
8:52:03 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
8:52:03 PM: Failed to upload file: next_migrate
8:52:03 PM: Site deploy was successfully initiated
8:52:04 PM: Execution cancelled
8:52:04 PM: Error running command: Command was cancelled
8:52:04 PM: Failing build: Failed to build site
8:52:04 PM: Finished processing build request in 6m52.729375946s
```

**Comment by quagliero** [comment] 2021-07-30 20:17
The functions section of the build was failing until I added the following dev dependencies (we don't use any of them...):

```js
  @react-three/fiber": "^7.0.6",
    "konva": "^8.1.1",
    "react-konva": "^17.0.2-5",
    "react-native": "^0.64.2",
    "react-zdog": "^1.0.11",
    "three": "^0.131.1",
    "zdog": "^1.1.2"
```

**Comment by lindsaylevine** [comment] 2021-07-30 21:29
have you tried the suggestions i made so far? aka esbuild/experimental-serverless-trace? (without the dependencies you add, obviously) @quagliero

**Comment by quagliero** [comment] 2021-07-30 21:36
@lindsaylevine we already had the experimental-serverless-trace in place. The esbuild node_bundler threw up some new errors so I just moved the server side function into client side (for now) so we can release the feature. I will update this thread shortly with the errors when using the node_bundler esbuild.

**Comment by quagliero** [comment] 2021-07-30 22:02
@lindsaylevine the following error occurs using node_bundler esbuild:

```bash
────────────────────────────────────────────────────────────────
  4. Functions bundling
────────────────────────────────────────────────────────────────

Packaging Functions from netlify/functions directory:
 - next_image/next_image.js
 - next_migrate/next_migrate.js

 > .netlify/plugins/node_modules/sharp/lib/output.js:4:22: error: No loader is configured for ".node" files: .netlify/plugins/node_modules/sharp/build/Release/sharp.node
    4 │ const sharp = require('../build/Release/sharp.node');
      ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


❯ Failed to bundle functions with selected bundler (fallback used):
   - next_image.zip

❯ The following Node.js modules use dynamic expressions to include files:
   - next
   - @ampproject/toolbox-optimizer

  Because files included with dynamic expressions aren't bundled with your serverless functions by default,
  this may result in an error when invoking a function. To resolve this error, you can mark these Node.js
  modules as external in the [functions] section of your `netlify.toml` configuration file:

  [functions]
    external_node_modules = ["next", "@ampproject/toolbox-optimizer"]
```

(I added the external_node_modules line)

**Comment by lindsaylevine** [comment] 2021-07-30 22:19
@quagliero ok. last question would be to try target serverless with esbuild. but, at this point, it seems like we're definitely going to need a repo that reproduces your issue!

**Comment by quagliero** [comment] 2021-07-30 22:25
@lindsaylevine Looks like a similar issue on svelte https://github.com/sveltejs/kit/issues/1547

**Comment by quagliero** [comment] 2021-07-30 22:43
I was able to solve it by adding `sharp` to the list of externals :) Along with @lindsaylevine suggestion of esbuild node_bundler. Total changes made:

```toml
# netlify.toml
[functions]
  # Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"
  external_node_modules = ["next", "@ampproject/toolbox-optimizer", "sharp"]
```

While using `target: 'experimental-serverless-trace',` in next.config.js.

Thanks for the help!

Please feel free to close this issue, cc @justincavery.

**Comment by justincavery** [comment] 2021-07-31 07:58
Thanks @quagliero and @lindsaylevine for getting this sorted.

**Closed** 2021-07-31 07:57 UTC
Labels: needs reproduction, type: bug
