### ISSUE TITLE
[Bug]: ERR_REQUIRE_ESM when using node-fetch v3

### ISSUE THREAD

**Issue by janakitti** [netlify/netlify-plugin-nextjs#752] opened 2021-10-28 13:42 UTC
### Steps to reproduce

When using the `node-fetch` v3 in an unrelated script in our app, the site successfully deploys, but we get the following error in the browser when visiting the deploy link:

```Must use import to load ES Module: /var/task/node_modules/node-fetch/src/index.js\nrequire() of ES modules is not supported.\nrequire() of /var/task/node_modules/node-fetch/src/index.js from /var/task/.netlify/functions-internal/___netlify-handler/___netlify-handler.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.\nInstead rename index.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/node_modules/node-fetch/package.json.\n```

It appears that Netlify is using `node-fetch` v2, which is built with CommonJS, whereas v3 is an ESM-only module.

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (netlify.toml)

**Comment by ascorbic** [comment] 2021-11-02 11:40
Thanks for the report. I'm closing it as a duplicate of #750. We should have a fix soon.

**Closed by ascorbic** 2021-11-02 11:40 UTC
Labels: type: bug
