### ISSUE TITLE
Build fails if firbase is used

### ISSUE THREAD

**Issue by KMKoushik** [netlify/netlify-plugin-nextjs#605] opened 2021-08-16 12:47 UTC
**Describe the bug**
I am using firebase for my next app and everything was working fine in local setup but immediately fails once I try to deploy it through netlify. Here's the log
```
@firebase/firestore: Firestore (8.8.1): INTERNAL UNHANDLED ERROR:  Error: ENOENT: no such file or directory, open '/opt/build/repo/packages/frontend/.next/serverless/protos/google/firestore/v1/firestore.proto'
5:09:30 PM:     at Object.openSync (fs.js:458:3)
5:09:30 PM:     at Object.readFileSync (fs.js:360:35)
5:09:30 PM:     at fetch (/opt/build/repo/packages/frontend/.next/serverless/chunks/657.js:95852:34)
5:09:30 PM:     at Root.load (/opt/build/repo/packages/frontend/.next/serverless/chunks/657.js:95886:13)
5:09:30 PM:     at Root.loadSync (/opt/build/repo/packages/frontend/.next/serverless/chunks/657.js:95927:17)
5:09:30 PM:     at Object.loadProtosWithOptionsSync (/opt/build/repo/packages/frontend/.next/serverless/chunks/657.js:59234:29)
5:09:30 PM:     at Object.loadSync (/opt/build/repo/packages/frontend/.next/serverless/chunks/657.js:59139:31)
5:09:30 PM:     at loadProtos (/opt/build/repo/packages/frontend/.next/serverless/chunks/657.js:32359:41)
5:09:30 PM:     at newConnection (/opt/build/repo/packages/frontend/.next/serverless/chunks/657.js:32380:18)
5:09:30 PM:     at OnlineComponentProvider.exports.modules.3180.OnlineComponentProvider.createDatastore (/opt/build/repo/packages/frontend/.next/serverless/chunks/657.js:37066:26)
5:09:30 PM: internal/process/promises.js:194
5:09:30 PM:         triggerUncaughtException(err, true /* fromPromise */);
5:09:30 PM:         ^
5:09:30 PM: Error: ENOENT: no such file or directory, open '/opt/build/repo/packages/frontend/.next/serverless/protos/google/firestore/v1/firestore.proto'
5:09:30 PM:     at Object.openSync (fs.js:458:3)
5:09:30 PM:     at Object.readFileSync (fs.js:360:35)
5:09:30 PM:     at fetch (/opt/build/repo/packages/frontend/.next/serverless/chunks/657.js:95852:34)
5:09:30 PM:     at Root.load (/opt/build/repo/packages/frontend/.next/serverless/chunks/657.js:95886:13)
5:09:30 PM:     at Root.loadSync (/opt/build/repo/packages/frontend/.next/serverless/chunks/657.js:95927:17)
5:09:30 PM:     at Object.loadProtosWithOptionsSync (/opt/build/repo/packages/frontend/.next/serverless/chunks/657.js:59234:29)
```

Note: I am using monorepo. Not sure if that has to do something with this.

**To Reproduce**
1. Add `firebase` as a dependency
2. Deploy it to netlify

**Expected behavior**
Should be deployed without any issue.

**Versions**
- Next.js: 11.0.1
- plugin (if installed at fixed version): 3.8.0

**If you're using the CLI to build**
 - OS: [e.g. macOS, Windows]
 - netlify/cli version:

**If you're using file-based installation**
--

**Comment by lindsaylevine** [comment] 2021-08-23 04:34
@koushikmohan1996 hey! thanks for opening this up with us. sounds like you have a pretty specific setup and that complicates us diagnosing this for you. i can't tell if this is a build/deploy error or a runtime error in a serverless function? i'm not sure why it would be missing the file `.next/serverless/protos/google/firestore/v1/firestore.proto` at build time, if your firebase integration/build is behaving as it should. have you tried building using the CLI? regardless, it's unfortunately a big stab in the dark for us to try to figure this out for you right now with the info we have. at the very least you should share build/deploy logs and your site configurations with us (netlify.toml, next.config.js, etc) and a deployed site if the issue is a runtime issue. your best bet would be to give us a deployable repo that reproduces the issue with your specific monorepo setup.

**Comment by koushikmohan1996** [comment] 2021-08-23 04:43
Thanks, @lindsaylevine for looking into this. It's not a runtime error and happens while building. 

Here is the build log: https://gist.github.com/koushikmohan1996/2e1d9224bc3d76ad93d1b0b8af19a681
next config: 
```
module.exports = {
  reactStrictMode: true,
}
```


I can create a deployable repo over this weekend.

**Comment by lindsaylevine** [comment] 2021-09-14 03:09
closing until repro is provided

**Closed by lindsaylevine** 2021-09-14 03:09 UTC
Labels: type: bug, priority: low, monorepo, needs reproduction
